<a href="https://colab.research.google.com/github/LCaravaggio/AnalisisCuantitativoAvanzado/blob/main/Regresi%C3%B3n/RegLin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from google.colab import userdata
import json

!mkdir ~/.kaggle
!touch ~/.kaggle/kaggle.json

api_token = {
    'username': userdata.get('KAGGLE_USER'),
    'key': userdata.get('KAGGLE_KEY')}
with open('/root/.kaggle/kaggle.json', 'w') as file:
    json.dump(api_token, file)

!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d quantbruce/real-estate-price-prediction

Dataset URL: https://www.kaggle.com/datasets/quantbruce/real-estate-price-prediction
License(s): other
  0% 0.00/6.98k [00:00<?, ?B/s]
100% 6.98k/6.98k [00:00<00:00, 3.42MB/s]


In [2]:
import zipfile
import os

os.listdir()

for file in os.listdir():
    if file.endswith('.zip'):
      zip_ref = zipfile.ZipFile(file, 'r')
      zip_ref.extractall()
      zip_ref.close()

In [3]:
df = pd.read_csv('/content/Real estate.csv')

In [4]:
df

No  X1 transaction date  X2 house age  \
0      1             2012.917          32.0   
1      2             2012.917          19.5   
2      3             2013.583          13.3   
3      4             2013.500          13.3   
4      5             2012.833           5.0   
..   ...                  ...           ...   
409  410             2013.000          13.7   
410  411             2012.667           5.6   
411  412             2013.250          18.8   
412  413             2013.000           8.1   
413  414             2013.500           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10   
1                                 306.59470                                9   
2                                 561.98450                                5   
3                                 561.98450                                5   
4                                 390.56840                                5   
..                                      ...                              ...   
409                              4082.01500                                0   
410                                90.45606                                9   
411                               390.96960                                7   
412                               104.81010                                5   
413                                90.45606                                9   

     X5 latitude  X6 longitude  Y house price of unit area  
0       24.98298     121.54024                        37.9  
1       24.98034     121.53951                        42.2  
2       24.98746     121.54391                        47.3  
3       24.98746     121.54391                        54.8  
4       24.97937     121.54245                        43.1  
..           ...           ...                         ...  
409     24.94155     121.50381                        15.4  
410     24.97433     121.54310                        50.0  
411     24.97923     121.53986                        40.6  
412     24.96674     121.54067                        52.5  
413     24.97433     121.54310                        63.9  

[414 rows x 8 columns]

In [5]:
# Con pocas líneas de código puedo correr una RL sobre los datos
from sklearn.linear_model import LinearRegression
X = df.drop('Y house price of unit area', axis=1)
y = df['Y house price of unit area']

reg = LinearRegression().fit(X, y)
score = reg.score(X, y)

In [6]:
score

0.5833632616324717

In [7]:
# Con esto puedo ver la relación, puedo buscar también hacer una predicción.
from sklearn.linear_model import LinearRegression
X = df.drop('Y house price of unit area', axis=1)
y = df['Y house price of unit area']

reg = LinearRegression().fit(X[:-1], y[:-1])
score = reg.score(X[:-1], y[:-1])

In [8]:
reg.predict(X[-1:])

array([52.87855662])

In [9]:
# Podría, como vimos, generar más variables
for x in X.columns:
    X['%s_2' % x] = X[x]*X[x]
    X['%s_3' % x] = X[x]**3
    X['%s_4' % x] = X[x]**4
    X['%s_5' % x] = X[x]**5

In [10]:
reg = LinearRegression().fit(X, y)
score = reg.score(X, y)

In [11]:
# El score debería mejorar
score

0.6778633901130766

In [ ]:
 # ¿Mejora la predicción?

In [12]:
reg = LinearRegression().fit(X[:-1], y[:-1])
score = reg.score(X[:-1], y[:-1])

In [13]:
score

0.6785082626619034

In [14]:
reg.predict(X[-1:])

array([54.91167491])

In [15]:
reg.coef_

array([ 5.55694007e-06, -7.30266553e-04, -2.35046138e-05, -5.88161889e-04,
        2.96763148e-05, -3.02759688e-11, -1.36043732e-11,  2.80319591e-04,
       -3.36209189e-06,  1.23377084e-08, -1.43039770e-11, -5.65324973e-10,
       -5.69191947e-07, -4.14836377e-07,  1.65007440e-10, -4.23365622e-04,
       -4.77929879e-03,  2.27905105e-04, -2.76834636e-06, -1.84225602e-05,
        1.10106302e-08, -2.26175671e-12,  1.53129271e-16,  1.90961716e-04,
        1.00961098e-03,  3.97728901e-03, -3.78106757e-04, -1.19235256e-10,
        4.33612363e-08,  3.02724571e-06,  1.43643948e-04, -3.57322649e-09,
       -4.34252414e-07, -3.51825254e-05,  2.09503101e-07])

In [16]:
from sklearn.model_selection import train_test_split
X = df.drop('Y house price of unit area', axis=1)
y = df['Y house price of unit area']
X_train, X_test, y_train, y_test=train_test_split(X,y)

In [17]:
reg = LinearRegression().fit(X_train, y_train)
score = reg.score(X_train, y_train)
score

0.6247027663311475

In [18]:
score = reg.score(X_test, y_test)
score

0.4546263492355146

In [19]:
X = df.drop('Y house price of unit area', axis=1)
y = df['Y house price of unit area']

In [20]:
for x in X.columns:
    X['%s_2' % x] = X[x]*X[x]
    X['%s_3' % x] = X[x]**3

In [21]:
X_train, X_test, y_train, y_test=train_test_split(X,y)

In [22]:
reg = LinearRegression().fit(X_train, y_train)
score = reg.score(X_train, y_train)
score

0.7355503849322476

In [23]:
score = reg.score(X_test, y_test)
score

0.5687565516155